= Demo for JPMS prez

JPMS stands for Java Platform Module System, aka Jigsaw.
It's the main feature of the Java 9 feature.

== Java 8

The demo application works with Java 8.

----
# Compile
./scripts/build.sh
# Run
./scripts/run.sh
----

Go to http://127.0.0.1/img

== Modular JDK

* Add module-info.java
* Build
* Update and run script run.sh

== Modular application

* Split into modules with the split-modules.sh
* Complete the module-info files : exports
* Update the build and run scripts

== Encapsulation

* Split backend into 3 modules (split-modules-backend.sh)
* Use exports ... to ...

Note : back to open at the end of the chapter.

== Dependency

* Mixed mode
** logs : switch to slf4j in fr.sw.fwk.common.Logger
** add dependencies in the module-path (compile)
** add dependencies/slf4j-simple in the class-path

== Service (optional)

* backend uses DAO
* inmem and db provide DAO
* clean dependencies in other modules

== Native

----
rm -rf target/main/image
$JAVA_HOME/bin/jlink \
        --module-path $JAVA_HOME/jmods:dependencies:target/main/artifact \
        --add-modules image.show,image.inmem \
        --launcher img=image.show/fr.sw.img.Main \
        --output target/main/image
----

=> module-info.class not found for slf4j.api module
=> revenir en arrière sur les logs